services:
  backend:
    build: ./backend
    volumes:
      - /Users/shinyasato/Documents/app/movie-night/backend:/app
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
  client:
    build: ./frontend
    volumes:
      - /Users/shinyasato/Documents/app/movie-night/frontend/src:/app/src
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
# docker build -t movie-night-backend .
# docker run --name movie-night-backend -v /Users/shinyasato/Documents/app/movie-night/backebd:/app --rm -d -p 8000:8000 movie-night-backend
# docker build -t movie-night-react .
# docker run --name movie-night-frontend -v /Users/shinyasato/Documents/app/movie-night/frontend/src:/app/src -v --rm -p 3000:3000 -it movie-night-frontend
