name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no pi@<YOUR_RASPBERRY_PI_IP> << 'EOF'
            cd /path/to/your/project
            docker-compose down
            git pull
            docker-compose up -d
          EOF
